/**
 * 우연의 발견 시드 카드 모음.
 *
 * 저작권 가드라인:
 *  - quote: 1925년 이전 작가(퍼블릭 도메인) 또는 한국어 의역
 *  - fact: 일반 상식/위키 공개 정보 의역
 *  - snippet: 오리지널 짧은 글
 *  - link: 공개 사이트 (광고·트래커 적은 것)
 *  - ritual / question / pairing: 오리지널
 *
 * 본문은 ≤ 280자 권장. 위젯 카드 + 모달 모두 깨지지 않도록.
 */
import type { SerendipityCard } from './types';

export const SEED_CARDS: SerendipityCard[] = [
  // ─────────────── quote (40) ───────────────
  { id: 'q-001', type: 'quote', body: '인생에서 중요한 것은 살아 있다는 것이다.', source: '— 알베르 카뮈', tags: ['삶'], origin: 'seed' },
  { id: 'q-002', type: 'quote', body: '바다를 보지 못한 사람은 바다를 두려워하지 않는다.', source: '— 미상', tags: ['용기'], origin: 'seed' },
  { id: 'q-003', type: 'quote', body: '천천히 가는 자가 가장 멀리 간다.', source: '— 동양 격언', tags: ['지혜'], origin: 'seed' },
  { id: 'q-004', type: 'quote', body: '내 영혼이 그늘진 정원이라면, 그 정원에도 분명 빛이 닿는 자리가 있다.', source: '— 라이너 마리아 릴케', tags: ['위로'], origin: 'seed' },
  { id: 'q-005', type: 'quote', body: '습관은 처음엔 거미줄 같지만 나중엔 강철 케이블이 된다.', source: '— 스페인 격언', tags: ['습관'], origin: 'seed' },
  { id: 'q-006', type: 'quote', body: '진정한 여행이란 새로운 풍경을 보는 것이 아니라 새로운 눈을 갖는 것이다.', source: '— 마르셀 프루스트', tags: ['시선'], origin: 'seed' },
  { id: 'q-007', type: 'quote', body: '오늘 누군가 그늘에 앉을 수 있는 것은 오래전 누군가 나무를 심었기 때문이다.', source: '— 워렌 버핏', tags: ['감사'], origin: 'seed' },
  { id: 'q-008', type: 'quote', body: '나는 실패하지 않았다. 단지 효과가 없는 만 가지 방법을 찾았을 뿐이다.', source: '— 토머스 에디슨', tags: ['실패'], origin: 'seed' },
  { id: 'q-009', type: 'quote', body: '존재하는 것은 변화하는 것이고, 변화하는 것은 성숙해지는 것이며, 성숙해지는 것은 자신을 끝없이 새로 만들어가는 것이다.', source: '— 앙리 베르그송', tags: ['변화'], origin: 'seed' },
  { id: 'q-010', type: 'quote', body: '우리는 우리가 반복하는 것이다.', source: '— 아리스토텔레스', tags: ['습관'], origin: 'seed' },
  { id: 'q-011', type: 'quote', body: '강한 것이 살아남는 것이 아니라, 살아남는 것이 강한 것이다.', source: '— 동양 격언', tags: ['생존'], origin: 'seed' },
  { id: 'q-012', type: 'quote', body: '평온한 바다는 결코 노련한 뱃사람을 만들지 못한다.', source: '— 영국 격언', tags: ['시련'], origin: 'seed' },
  { id: 'q-013', type: 'quote', body: '아름다움은 보는 사람의 눈 속에 있다.', source: '— 데이비드 흄', tags: ['미학'], origin: 'seed' },
  { id: 'q-014', type: 'quote', body: '내가 멀리 보았다면 그것은 거인의 어깨 위에 서 있었기 때문이다.', source: '— 아이작 뉴턴', tags: ['겸손'], origin: 'seed' },
  { id: 'q-015', type: 'quote', body: '인생은 가까이서 보면 비극이고, 멀리서 보면 희극이다.', source: '— 찰리 채플린', tags: ['관점'], origin: 'seed' },
  { id: 'q-016', type: 'quote', body: '아는 것이 힘이다.', source: '— 프랜시스 베이컨', tags: ['지식'], origin: 'seed' },
  { id: 'q-017', type: 'quote', body: '느리게 가는 것을 두려워하지 말고, 가만히 서 있는 것을 두려워하라.', source: '— 중국 격언', tags: ['지속'], origin: 'seed' },
  { id: 'q-018', type: 'quote', body: '아직 일어나지 않은 일을 미리 걱정하느라 오늘을 잃지 마라.', source: '— 미상', tags: ['현재'], origin: 'seed' },
  { id: 'q-019', type: 'quote', body: '우리가 만나는 모든 사람은 우리에게 무언가 가르쳐줄 것이 있다.', source: '— 미상', tags: ['관계'], origin: 'seed' },
  { id: 'q-020', type: 'quote', body: '여행의 끝에서 우리는 떠난 곳에 다시 도착해, 처음으로 그곳을 본다.', source: '— T.S. 엘리엇', tags: ['여행'], origin: 'seed' },
  { id: 'q-021', type: 'quote', body: '두 번 읽을 가치가 없는 책은 한 번 읽을 가치도 없다.', source: '— 카를 빌헬름 폰 슐레겔', tags: ['독서'], origin: 'seed' },
  { id: 'q-022', type: 'quote', body: '인간은 자신이 행복하다는 것을 알지 못한 채 행복할 수 있다.', source: '— 표도르 도스토옙스키', tags: ['행복'], origin: 'seed' },
  { id: 'q-023', type: 'quote', body: '용기는 두려움이 없는 것이 아니라, 두려움보다 더 중요한 무언가가 있다는 판단이다.', source: '— 앰브로즈 레드문', tags: ['용기'], origin: 'seed' },
  { id: 'q-024', type: 'quote', body: '말하기 전에 들어라. 쓰기 전에 생각하라.', source: '— 윌리엄 아서 워드', tags: ['소통'], origin: 'seed' },
  { id: 'q-025', type: 'quote', body: '시간은 인간이 쓸 수 있는 가장 값진 재산이다.', source: '— 테오프라스토스', tags: ['시간'], origin: 'seed' },
  { id: 'q-026', type: 'quote', body: '단순함은 궁극의 정교함이다.', source: '— 레오나르도 다 빈치', tags: ['디자인'], origin: 'seed' },
  { id: 'q-027', type: 'quote', body: '우리는 보이는 것을 보는 것이 아니라, 보고 싶은 것을 본다.', source: '— 아나이스 닌', tags: ['시선'], origin: 'seed' },
  { id: 'q-028', type: 'quote', body: '생각을 바꾸면 세계를 바꿀 수 있다.', source: '— 노먼 빈센트 필', tags: ['태도'], origin: 'seed' },
  { id: 'q-029', type: 'quote', body: '내일은 또 다른 하루다.', source: '— 마거릿 미첼', tags: ['희망'], origin: 'seed' },
  { id: 'q-030', type: 'quote', body: '내가 무엇을 모르는지 아는 것이 진정한 앎이다.', source: '— 소크라테스', tags: ['겸손'], origin: 'seed' },
  { id: 'q-031', type: 'quote', body: '시작이 반이다.', source: '— 아리스토텔레스', tags: ['시작'], origin: 'seed' },
  { id: 'q-032', type: 'quote', body: '실패는 성공의 어머니다.', source: '— 동양 격언', tags: ['실패'], origin: 'seed' },
  { id: 'q-033', type: 'quote', body: '읽지 않은 책 한 권은 도끼와 같다 — 우리 안의 얼어붙은 바다를 깨뜨리는.', source: '— 프란츠 카프카', tags: ['독서'], origin: 'seed' },
  { id: 'q-034', type: 'quote', body: '오늘 할 수 있는 일을 내일로 미루지 마라.', source: '— 벤자민 프랭클린', tags: ['실행'], origin: 'seed' },
  { id: 'q-035', type: 'quote', body: '강물이 바다를 만나려면 굽이쳐야 한다.', source: '— 미상', tags: ['우회'], origin: 'seed' },
  { id: 'q-036', type: 'quote', body: '글을 쓰는 것은 자기 자신을 두 번 사는 일이다.', source: '— 나탈리 골드버그', tags: ['글쓰기'], origin: 'seed' },
  { id: 'q-037', type: 'quote', body: '나무는 한 그루만으로 숲이 되지 않는다.', source: '— 아프리카 격언', tags: ['공동체'], origin: 'seed' },
  { id: 'q-038', type: 'quote', body: '꿈을 미루지 마라. 마음에 품은 것이 가장 빨리 늙는다.', source: '— 미상', tags: ['실행'], origin: 'seed' },
  { id: 'q-039', type: 'quote', body: '가장 어두운 밤도 끝이 있고, 해는 다시 떠오를 것이다.', source: '— 빅토르 위고', tags: ['희망'], origin: 'seed' },
  { id: 'q-040', type: 'quote', body: '천 리 길도 한 걸음부터.', source: '— 노자', tags: ['시작'], origin: 'seed' },

  // ─────────────── fact (30) ───────────────
  { id: 'f-001', type: 'fact', title: '문어의 심장은 셋', body: '문어는 심장을 세 개 가지고 있다. 그중 두 개는 아가미로, 한 개는 몸 전체로 피를 보낸다. 헤엄칠 때는 몸쪽 심장이 멈추기 때문에, 문어는 헤엄보다 걷는 것을 더 좋아한다.', tags: ['생물'], origin: 'seed' },
  { id: 'f-002', type: 'fact', title: '꿀은 부패하지 않는다', body: '낮은 수분 함량과 높은 산성도 덕분에 꿀은 영원히 보관된다. 이집트 피라미드에서 발견된 3,000년 된 꿀도 여전히 먹을 수 있는 상태였다.', tags: ['음식'], origin: 'seed' },
  { id: 'f-003', type: 'fact', title: '바나나는 과학적으로 베리', body: '딸기는 베리(berry)가 아니지만, 바나나는 베리다. 식물학적 정의에 따르면 베리는 한 송이의 꽃에서 자란 단일 씨방으로 만들어진 과일이다.', tags: ['과학'], origin: 'seed' },
  { id: 'f-004', type: 'fact', title: '하루 35,000번의 결정', body: '평균적으로 성인은 하루에 약 35,000번의 결정을 내린다. 그중 점심 메뉴에 관한 것만 200번이라는 연구도 있다.', tags: ['뇌'], origin: 'seed' },
  { id: 'f-005', type: 'fact', title: '소금쟁이가 물 위를 걷는 이유', body: '소금쟁이의 다리는 미세한 털로 덮여 있어 표면장력이 깨지지 않는다. 그래서 물 위를 떠다닐 수 있다.', tags: ['과학'], origin: 'seed' },
  { id: 'f-006', type: 'fact', title: '에펠탑은 여름에 더 크다', body: '철은 더위에 팽창한다. 더운 여름엔 에펠탑이 약 15cm 더 길어진다.', tags: ['건축'], origin: 'seed' },
  { id: 'f-007', type: 'fact', title: '거북이의 호흡', body: '몇몇 거북이 종은 항문으로 호흡할 수 있다. 겨울잠 동안 산소가 부족한 물속에서 살아남는 방법이다.', tags: ['생물'], origin: 'seed' },
  { id: 'f-008', type: 'fact', title: '우주의 냄새', body: '우주복에서 돌아온 우주비행사들은 우주의 냄새를 "탄 고기와 금속" 같다고 묘사한다.', tags: ['우주'], origin: 'seed' },
  { id: 'f-009', type: 'fact', title: '눈은 오각형이 아니다', body: '눈송이는 항상 6각형이다. 물 분자의 결정 구조 때문에 6방향으로만 자란다.', tags: ['자연'], origin: 'seed' },
  { id: 'f-010', type: 'fact', title: '코끼리는 점프를 못한다', body: '몸무게 때문에 코끼리는 네 발이 동시에 땅에서 떨어지는 점프를 할 수 없다. 대신 빠르게 걷는다.', tags: ['생물'], origin: 'seed' },
  { id: 'f-011', type: 'fact', title: '바다거북의 성별', body: '바다거북의 성별은 알이 묻힌 모래의 온도로 결정된다. 따뜻하면 암컷, 차가우면 수컷.', tags: ['생물'], origin: 'seed' },
  { id: 'f-012', type: 'fact', title: '인간의 뇌는 컴퓨터처럼 잠들지 않는다', body: '뇌의 일부는 자는 동안에도 활발하게 작동한다. 특히 기억 정리는 깊은 수면 중에 일어난다.', tags: ['뇌'], origin: 'seed' },
  { id: 'f-013', type: 'fact', title: '목성은 별이 될 뻔했다', body: '목성이 지금보다 약 80배 무거웠다면 별이 되었을 것이다. 우리 태양계는 두 개의 별을 가진 쌍성계가 될 수 있었다.', tags: ['우주'], origin: 'seed' },
  { id: 'f-014', type: 'fact', title: '플라밍고가 분홍색인 이유', body: '플라밍고는 원래 회색으로 태어난다. 새우와 조류를 먹으면서 그 안의 베타카로틴이 깃털을 분홍으로 물들인다.', tags: ['생물'], origin: 'seed' },
  { id: 'f-015', type: 'fact', title: '책 한 권에 들어간 숫자', body: '한국인은 평균적으로 1년에 약 7권의 책을 읽는다. OECD 평균보다 적지만, 짧은 글까지 합치면 다른 양상이다.', tags: ['독서'], origin: 'seed' },
  { id: 'f-016', type: 'fact', title: '하품은 전염된다', body: '다른 사람이 하품하는 걸 보면 약 60%의 사람이 따라 하품한다. 공감 능력이 높을수록 더 잘 옮는다는 연구도 있다.', tags: ['뇌'], origin: 'seed' },
  { id: 'f-017', type: 'fact', title: '심장은 평생 30억 번', body: '평균적인 사람의 심장은 평생 약 30억 번 뛴다. 1분에 70번씩 70년이면 그 정도가 된다.', tags: ['몸'], origin: 'seed' },
  { id: 'f-018', type: 'fact', title: '제일 오래된 살아있는 나무', body: '캘리포니아의 한 브리슬콘 소나무는 약 4,800년을 살아왔다. 이집트 피라미드보다 오래됐다.', tags: ['자연'], origin: 'seed' },
  { id: 'f-019', type: 'fact', title: '달은 매년 멀어진다', body: '달은 지구로부터 매년 약 3.8cm씩 멀어지고 있다. 수십억 년 후엔 일식이 더 이상 일어나지 않을 것이다.', tags: ['우주'], origin: 'seed' },
  { id: 'f-020', type: 'fact', title: '잠을 자는 동안 키가 큰다', body: '척추의 디스크는 낮 동안 압축됐다가 잘 때 회복된다. 그래서 아침이 저녁보다 1cm 정도 키가 크다.', tags: ['몸'], origin: 'seed' },
  { id: 'f-021', type: 'fact', title: '소리는 물에서 더 빠르다', body: '소리는 공기 중에서 초속 343m, 물에서는 1,480m로 약 4배 빠르게 전달된다.', tags: ['과학'], origin: 'seed' },
  { id: 'f-022', type: 'fact', title: '파인애플은 거꾸로 거꾸로', body: '파인애플은 나무가 아니라 풀에서 자란다. 한 그루의 풀에서 1년에 한 개의 열매만 맺는다.', tags: ['음식'], origin: 'seed' },
  { id: 'f-023', type: 'fact', title: '눈동자가 떨리는 이유', body: '눈은 가만히 있지 않고 1초에 수십 번 미세하게 움직인다. 이 떨림(saccade)이 없으면 시야가 흐려진다.', tags: ['몸'], origin: 'seed' },
  { id: 'f-024', type: 'fact', title: '한국어의 단모음', body: '한국어는 단모음 10개를 가진다. 영어(약 12개)보다 적지만 일본어(5개)보다는 훨씬 다양하다.', tags: ['언어'], origin: 'seed' },
  { id: 'f-025', type: 'fact', title: '커피의 절반', body: '세계에서 자라는 커피의 약 60%는 단 한 가지 종, 아라비카다. 기후변화에 약해 미래가 위태롭다.', tags: ['음식'], origin: 'seed' },
  { id: 'f-026', type: 'fact', title: '거울 속의 나는 좌우가 바뀌지 않는다', body: '거울은 좌우가 아니라 앞뒤를 바꾼다. 우리가 좌우로 인식하는 것은 뇌의 해석 차이다.', tags: ['과학'], origin: 'seed' },
  { id: 'f-027', type: 'fact', title: '벌은 사각형을 좋아한다', body: '벌집이 육각형인 이유는 같은 양의 밀랍으로 가장 넓은 공간을 만들기 때문이다 — 자연의 효율 디자인.', tags: ['자연'], origin: 'seed' },
  { id: 'f-028', type: 'fact', title: '인간의 후각', body: '인간은 약 1조 가지의 냄새를 구별할 수 있다고 추정된다. 색깔(약 1,000만)보다 훨씬 많다.', tags: ['몸'], origin: 'seed' },
  { id: 'f-029', type: 'fact', title: '빛은 1초에 7바퀴', body: '빛은 진공에서 1초에 약 30만 km를 간다. 지구 둘레를 7바퀴 반 도는 거리다.', tags: ['과학'], origin: 'seed' },
  { id: 'f-030', type: 'fact', title: '북극곰의 피부는 검다', body: '북극곰의 흰 털은 비어 있어서 빛을 산란시킨다. 그 아래 피부는 검어서 햇빛의 열을 흡수한다.', tags: ['생물'], origin: 'seed' },

  // ─────────────── snippet (30) ───────────────
  { id: 's-001', type: 'snippet', body: '오래 만나지 못한 친구의 안부가 갑자기 궁금해질 때가 있다. 그건 그가 당신을 떠올렸다는 신호일지도 모른다. 마음은 보이지 않는 실로 이어져 있어서, 한쪽이 당기면 반대쪽도 흔들린다.', tags: ['관계'], origin: 'seed' },
  { id: 's-002', type: 'snippet', body: '책상 위의 먼지를 닦는 것만으로도 마음이 맑아진다. 정리는 공간을 바꾸기보다 머릿속을 바꾸는 일에 가깝다.', tags: ['일상'], origin: 'seed' },
  { id: 's-003', type: 'snippet', body: '커피 한 잔의 시간은 짧지만, 그 사이에 떠올린 생각은 하루를 바꾼다. 우리는 무언가를 결정할 때 의외로 작은 순간에 기댄다.', tags: ['일상'], origin: 'seed' },
  { id: 's-004', type: 'snippet', body: '비 오는 날의 글씨는 평소보다 조금 더 정성스럽다. 종이가 기다려주는 것 같은 기분이 든다.', tags: ['글쓰기'], origin: 'seed' },
  { id: 's-005', type: 'snippet', body: '실패한 다음 날의 햇살은 묘하게 더 부드럽다. 마치 세상이 당신을 다시 안아주는 것처럼.', tags: ['위로'], origin: 'seed' },
  { id: 's-006', type: 'snippet', body: '오래 산 동네일수록 길을 잃는다. 너무 익숙해서 보지 않게 되니까. 가끔은 첫날의 눈으로 다시 걸어볼 필요가 있다.', tags: ['시선'], origin: 'seed' },
  { id: 's-007', type: 'snippet', body: '잠들기 직전에 떠오른 좋은 문장은 거의 항상 사라진다. 그래서 어떤 작가들은 머리맡에 종이를 둔다.', tags: ['글쓰기'], origin: 'seed' },
  { id: 's-008', type: 'snippet', body: '지나간 사진을 보면 그때는 평범했던 날이 가장 빛나 보인다. 행복은 항상 지나간 뒤에 정체를 드러낸다.', tags: ['시간'], origin: 'seed' },
  { id: 's-009', type: 'snippet', body: '바람이 부는 방향을 바꿀 수는 없지만, 돛은 우리가 조절한다. 운명은 풍향이 아니라 항해의 기술이다.', tags: ['태도'], origin: 'seed' },
  { id: 's-010', type: 'snippet', body: '오래된 음악을 들으면 그 시절의 향기가 함께 온다. 기억은 시각보다 청각에 더 깊이 새겨지는 모양이다.', tags: ['음악'], origin: 'seed' },
  { id: 's-011', type: 'snippet', body: '빈 노트를 펼치는 것은 작은 용기를 필요로 한다. 첫 줄을 쓰는 사람은 결국 책을 완성하는 사람이다.', tags: ['글쓰기'], origin: 'seed' },
  { id: 's-012', type: 'snippet', body: '느슨하게 시간을 보내는 일에 죄책감을 가질 필요는 없다. 풀밭이 잠시 마르는 것은 다음 비를 더 깊이 받기 위해서다.', tags: ['휴식'], origin: 'seed' },
  { id: 's-013', type: 'snippet', body: '같은 하늘을 보더라도 마음의 색깔에 따라 다른 풍경이 된다. 세상은 당신이 보는 만큼만 보인다.', tags: ['시선'], origin: 'seed' },
  { id: 's-014', type: 'snippet', body: '도시의 새벽 4시는 아주 잠시, 누구의 것도 아닌 시간이다. 그 짧은 적막을 알게 되면 도시가 다르게 보이기 시작한다.', tags: ['도시'], origin: 'seed' },
  { id: 's-015', type: 'snippet', body: '말로 다 못한 것을 침묵이 대신 전한다. 깊은 사이일수록 말의 양이 줄어든다.', tags: ['관계'], origin: 'seed' },
  { id: 's-016', type: 'snippet', body: '낯선 길을 걷는 것은 뇌에게 작은 여행을 선물하는 일이다. 매일 같은 출근길에서 다른 골목을 한 번 시도해보라.', tags: ['일상'], origin: 'seed' },
  { id: 's-017', type: 'snippet', body: '오늘 만난 누군가가 내일도 곁에 있으리라는 보장은 없다. 그래서 인사는 가능한 한 따뜻하게 하는 게 좋다.', tags: ['관계'], origin: 'seed' },
  { id: 's-018', type: 'snippet', body: '식물에 물을 주는 일은 작은 약속을 지키는 연습이다. 매일 같은 시간에, 잊지 않고, 누구도 보지 않아도.', tags: ['일상'], origin: 'seed' },
  { id: 's-019', type: 'snippet', body: '오랜만에 만난 친구가 변하지 않은 것도 좋고, 변한 것도 좋다. 사람은 그대로 있을 권리도, 다른 사람이 될 권리도 있다.', tags: ['관계'], origin: 'seed' },
  { id: 's-020', type: 'snippet', body: '낙엽은 떨어지는 것이 아니라, 다음 봄을 위해 자리를 비워주는 것이다. 끝맺음에는 항상 그런 의도가 숨어 있다.', tags: ['계절'], origin: 'seed' },
  { id: 's-021', type: 'snippet', body: '한 번도 해보지 않은 일이 있다는 건, 아직 발견하지 않은 자기 자신이 있다는 뜻이다.', tags: ['도전'], origin: 'seed' },
  { id: 's-022', type: 'snippet', body: '오래된 책의 여백에 적힌 다른 사람의 메모는 시간을 건너온 편지처럼 느껴진다.', tags: ['독서'], origin: 'seed' },
  { id: 's-023', type: 'snippet', body: '가끔 일부러 길을 잘못 들어보면, 평생 못 봤을 풍경 하나가 기다리고 있다.', tags: ['우연'], origin: 'seed' },
  { id: 's-024', type: 'snippet', body: '진짜 휴식은 아무것도 하지 않는 것이 아니라, 의무에서 자유로워지는 것이다.', tags: ['휴식'], origin: 'seed' },
  { id: 's-025', type: 'snippet', body: '낯선 도시의 카페에 앉아 있으면, 오랫동안 잊고 지낸 자기 자신을 다시 만나곤 한다.', tags: ['여행'], origin: 'seed' },
  { id: 's-026', type: 'snippet', body: '오랫동안 미뤄둔 일은 대개 30분이면 끝난다. 미루는 시간이 일하는 시간보다 길다.', tags: ['실행'], origin: 'seed' },
  { id: 's-027', type: 'snippet', body: '글을 쓴다는 건 자신이 무엇을 생각하는지 발견하는 일이다. 머릿속에 있을 땐 모호하던 것이 손끝을 지나면 형태를 얻는다.', tags: ['글쓰기'], origin: 'seed' },
  { id: 's-028', type: 'snippet', body: '오래된 노래는 한 번 들으면, 그 시절을 통째로 데려온다. 음악은 시간을 압축하는 유일한 매체다.', tags: ['음악'], origin: 'seed' },
  { id: 's-029', type: 'snippet', body: '비 오는 날 우산이 없을 때, 굳이 뛰지 않으면 어쩐지 더 안 젖는 기분이 든다. 받아들임에는 이상한 효율이 있다.', tags: ['태도'], origin: 'seed' },
  { id: 's-030', type: 'snippet', body: '내가 좋아하는 것 열 가지를 적어보면, 그게 곧 나라는 사람의 지도가 된다.', tags: ['자기이해'], origin: 'seed' },

  // ─────────────── link (20) ───────────────
  { id: 'l-001', type: 'link', title: 'Radio Garden', body: '지구본을 돌리며 전 세계 도시의 라디오를 실시간으로 듣는다. 도쿄에서 카이로로, 부에노스아이레스에서 헬싱키로.', url: 'https://radio.garden/', tags: ['음악','발견'], origin: 'seed' },
  { id: 'l-002', type: 'link', title: 'Window Swap', body: '낯선 사람의 창문 너머 풍경을 본다. 누군가의 하루를 잠시 빌려보는 것 같다.', url: 'https://www.window-swap.com/', tags: ['풍경'], origin: 'seed' },
  { id: 'l-003', type: 'link', title: 'A Soft Murmur', body: '비, 천둥, 카페, 모닥불 같은 백색 소음을 직접 섞어 만드는 도구. 집중이 필요할 때.', url: 'https://asoftmurmur.com/', tags: ['소리'], origin: 'seed' },
  { id: 'l-004', type: 'link', title: 'The Useless Web', body: '버튼 한 번에 의미 없이 즐거운 사이트로 데려간다. 인터넷의 90년대 정신.', url: 'https://theuselessweb.com/', tags: ['재미'], origin: 'seed' },
  { id: 'l-005', type: 'link', title: 'Pudding.cool', body: '저널리즘과 데이터 시각화가 만난 곳. 한 번 들어가면 한 시간이 사라진다.', url: 'https://pudding.cool/', tags: ['읽을거리'], origin: 'seed' },
  { id: 'l-006', type: 'link', title: 'Internet Archive', body: '오래된 책·영화·음악·웹페이지를 보관하는 디지털 도서관. 1996년의 인터넷도 여기 있다.', url: 'https://archive.org/', tags: ['아카이브'], origin: 'seed' },
  { id: 'l-007', type: 'link', title: 'Zen Sound', body: '정원에서 들려올 법한 소리들 — 바람, 빗방울, 종소리.', url: 'https://www.zen-sound.com/', tags: ['소리'], origin: 'seed' },
  { id: 'l-008', type: 'link', title: 'Are.na', body: '핀터레스트 같지만 광고 없고 알고리즘 없는 큐레이션 공간. 진짜로 영감 받고 싶을 때.', url: 'https://are.na/', tags: ['영감'], origin: 'seed' },
  { id: 'l-009', type: 'link', title: 'Wikipedia 무작위 글', body: '위키피디아가 임의의 글로 데려간다. 알게 될 것을 미리 알지 못하는 즐거움.', url: 'https://ko.wikipedia.org/wiki/%ED%8A%B9%EC%88%98:%EC%9E%84%EC%9D%98%EB%AC%B8%EC%84%9C', tags: ['지식'], origin: 'seed' },
  { id: 'l-010', type: 'link', title: 'My Noise', body: '복잡한 소음 마스킹 도구. 도서관·기차·해변 등 수십 가지 환경 소리를 정밀 조절.', url: 'https://mynoise.net/', tags: ['소리'], origin: 'seed' },
  { id: 'l-011', type: 'link', title: 'Drawastickman', body: '막대 사람을 그리면 모험을 떠난다. 5분의 동심.', url: 'https://www.drawastickman.com/', tags: ['놀이'], origin: 'seed' },
  { id: 'l-012', type: 'link', title: '구글 어스 — 무작위 위치', body: '지구 어딘가의 풍경으로 순간 이동. 고비 사막에 떨어지면 그 자체로 명상.', url: 'https://earth.google.com/', tags: ['풍경'], origin: 'seed' },
  { id: 'l-013', type: 'link', title: 'NASA APOD', body: '하루에 한 장, 천체 사진 + 짧은 설명. 우주는 매일 다른 얼굴이다.', url: 'https://apod.nasa.gov/apod/astropix.html', tags: ['우주'], origin: 'seed' },
  { id: 'l-014', type: 'link', title: 'Patatap', body: '키보드를 누르면 색과 소리가 동시에 튀어나오는 시각·청각 장난감.', url: 'https://patatap.com/', tags: ['놀이'], origin: 'seed' },
  { id: 'l-015', type: 'link', title: '100 Rabbits', body: '배 위에서 살며 도구와 글을 만드는 두 사람의 기록. 단순함의 미학.', url: 'https://100r.co/', tags: ['삶'], origin: 'seed' },
  { id: 'l-016', type: 'link', title: 'Rainy Mood', body: '빗소리 하나로 모든 게 정리된다. 가장 단순한 사이트가 가장 오래 남는다.', url: 'https://rainymood.com/', tags: ['소리'], origin: 'seed' },
  { id: 'l-017', type: 'link', title: 'Public Domain Review', body: '저작권이 풀린 옛 문서·이미지·영상의 큐레이션. 1800년대 일러스트북이 무료다.', url: 'https://publicdomainreview.org/', tags: ['아카이브'], origin: 'seed' },
  { id: 'l-018', type: 'link', title: 'A Year of Books', body: '하루 한 페이지씩, 1년 동안 한 권. 천천히 읽는 즐거움을 다시 가르쳐주는 사이트.', url: 'https://ayearofbooks.net/', tags: ['독서'], origin: 'seed' },
  { id: 'l-019', type: 'link', title: 'Ambient Mixer', body: '직접 만든 환경 소리를 공유하는 커뮤니티. "호그와트 도서관" 같은 테마도 있다.', url: 'https://www.ambient-mixer.com/', tags: ['소리'], origin: 'seed' },
  { id: 'l-020', type: 'link', title: 'Quick, Draw!', body: 'AI에게 그림을 그려 보여주는 게임. 막대 그림을 얼마나 잘 알아맞히는지 시험해보자.', url: 'https://quickdraw.withgoogle.com/', tags: ['놀이'], origin: 'seed' },

  // ─────────────── ritual (15) ───────────────
  { id: 'r-001', type: 'ritual', title: '창문 1분 환기', body: '하던 일을 멈추고 창문을 열어 1분간 바깥 공기를 들이마신다. 기분과 집중력이 동시에 회복된다.', tags: ['리셋'], origin: 'seed' },
  { id: 'r-002', type: 'ritual', title: '20-20-20', body: '20분마다 20초 동안 20피트(약 6m) 거리의 무언가를 본다. 눈의 피로가 절반으로 줄어든다.', tags: ['건강'], origin: 'seed' },
  { id: 'r-003', type: 'ritual', title: '물 한 컵', body: '커피 대신 물 한 컵을 천천히 마신다. 5분간 손에서 다른 일을 놓는다.', tags: ['건강'], origin: 'seed' },
  { id: 'r-004', type: 'ritual', title: '책상 정리', body: '책상 위 물건 3가지를 제자리에 둔다. 마음 정리는 공간 정리에서 시작된다.', tags: ['정리'], origin: 'seed' },
  { id: 'r-005', type: 'ritual', title: '하늘 한 번', body: '눈을 들어 하늘을 본다. 구름이 어떤 모양인지 한 문장으로 묘사해본다.', tags: ['시선'], origin: 'seed' },
  { id: 'r-006', type: 'ritual', title: '깊게 세 번', body: '눈을 감고 깊게 세 번 숨쉰다. 들이쉴 때 4초, 멈추고 4초, 내쉴 때 4초.', tags: ['호흡'], origin: 'seed' },
  { id: 'r-007', type: 'ritual', title: '손목 굴리기', body: '키보드를 떠나 양 손목을 천천히 10번씩 돌린다. 뻐근함이 풀린다.', tags: ['건강'], origin: 'seed' },
  { id: 'r-008', type: 'ritual', title: '오늘의 한 단어', body: '지금 머릿속을 한 단어로 정리해본다. 그 단어가 오늘의 색깔이 된다.', tags: ['자기이해'], origin: 'seed' },
  { id: 'r-009', type: 'ritual', title: '귀 비우기', body: '음악과 알림을 모두 끄고 30초간 주변 소리를 듣는다. 평소엔 들리지 않던 것들이 들린다.', tags: ['감각'], origin: 'seed' },
  { id: 'r-010', type: 'ritual', title: '걸어서 한 바퀴', body: '의자에서 일어나 사무실(또는 방)을 한 바퀴 천천히 걷는다. 다리에 피가 도는 느낌을 즐겨본다.', tags: ['건강'], origin: 'seed' },
  { id: 'r-011', type: 'ritual', title: '문구 한 줄 옮겨 적기', body: '좋아하는 책의 한 문장을 손으로 옮겨 적는다. 머리가 아니라 손이 그 문장을 기억한다.', tags: ['글쓰기'], origin: 'seed' },
  { id: 'r-012', type: 'ritual', title: '5분 빈둥', body: '아무 목적 없이 5분 동안 멍하게 있는다. 뇌의 기본 모드가 아이디어를 정리한다.', tags: ['휴식'], origin: 'seed' },
  { id: 'r-013', type: 'ritual', title: '감사 세 가지', body: '눈에 보이는 것 중 감사한 것 셋을 마음속으로 꼽는다. 작아도 좋다.', tags: ['감사'], origin: 'seed' },
  { id: 'r-014', type: 'ritual', title: '안 본 단톡방 무시', body: '오늘 한 단톡방의 알림을 끈다. 모든 대화에 답할 의무는 없다.', tags: ['디지털'], origin: 'seed' },
  { id: 'r-015', type: 'ritual', title: '내일 첫 일 정하기', body: '잠들기 전 내일 가장 먼저 할 한 가지만 적어둔다. 아침에 결정을 아낀다.', tags: ['실행'], origin: 'seed' },

  // ─────────────── question (15) ───────────────
  { id: 'qq-001', type: 'question', body: '10년 뒤 오늘, 당신은 어디서 어떤 모습일 것 같은가요?', tags: ['미래'], origin: 'seed' },
  { id: 'qq-002', type: 'question', body: '최근에 마지막으로 마음껏 웃은 순간은 언제였나요?', tags: ['기쁨'], origin: 'seed' },
  { id: 'qq-003', type: 'question', body: '지금 1억 원이 생긴다면, 가장 먼저 무엇을 하시겠어요?', tags: ['상상'], origin: 'seed' },
  { id: 'qq-004', type: 'question', body: '어렸을 때의 자신이 지금의 당신을 본다면 뭐라고 할까요?', tags: ['자기이해'], origin: 'seed' },
  { id: 'qq-005', type: 'question', body: '오늘 가장 신경 쓰이는 한 가지는 무엇인가요? 그것을 다섯 단어로 말해본다면?', tags: ['현재'], origin: 'seed' },
  { id: 'qq-006', type: 'question', body: '시간이 무한하다면, 한 번도 해본 적 없는 어떤 일을 해보고 싶나요?', tags: ['상상'], origin: 'seed' },
  { id: 'qq-007', type: 'question', body: '당신이 가진 가장 자랑스러운 흉터는 무엇인가요? 몸의 것이든 마음의 것이든.', tags: ['자기이해'], origin: 'seed' },
  { id: 'qq-008', type: 'question', body: '오늘 가장 친절했던 순간은 언제였나요?', tags: ['관계'], origin: 'seed' },
  { id: 'qq-009', type: 'question', body: '지금 당장 누군가에게 미안하다고 말해야 할 사람이 있나요?', tags: ['관계'], origin: 'seed' },
  { id: 'qq-010', type: 'question', body: '한 가지 능력을 무료로 얻을 수 있다면, 무엇을 고르겠어요?', tags: ['상상'], origin: 'seed' },
  { id: 'qq-011', type: 'question', body: '죽기 전에 꼭 가보고 싶은 도시는 어디인가요?', tags: ['여행'], origin: 'seed' },
  { id: 'qq-012', type: 'question', body: '당신을 가장 잘 아는 사람은 누구이고, 그 사람은 당신을 어떻게 묘사할까요?', tags: ['관계'], origin: 'seed' },
  { id: 'qq-013', type: 'question', body: '오늘 했지만 안 했어도 괜찮았을 일은 무엇인가요?', tags: ['시간'], origin: 'seed' },
  { id: 'qq-014', type: 'question', body: '가장 마지막으로 처음 해본 일은 무엇이었나요?', tags: ['도전'], origin: 'seed' },
  { id: 'qq-015', type: 'question', body: '내일 출근(등교)을 하지 않아도 된다면, 그 하루를 어떻게 보내고 싶나요?', tags: ['휴식'], origin: 'seed' },

  // ─────────────── pairing (10) ───────────────
  { id: 'p-001', type: 'pairing', title: '비 오는 날 + 무라카미 하루키', body: '"노르웨이의 숲" 한 챕터 + 빗소리 + 따뜻한 차 한 잔. 일요일 오후의 완벽한 조합.', tags: ['책','분위기'], origin: 'seed' },
  { id: 'p-002', type: 'pairing', title: '에릭 사티 + 새벽 4시', body: '"짐노페디 1번" 을 도시가 잠든 시간에 듣는다. 음악은 시간대를 만나서 비로소 완성된다.', tags: ['음악','시간'], origin: 'seed' },
  { id: 'p-003', type: 'pairing', title: '"인사이드 아웃" + 일기 쓰기', body: '영화를 보고 난 그날 밤, 지금의 감정을 색깔과 모양으로 적어본다. 기억이 더 오래 남는다.', tags: ['영화','일기'], origin: 'seed' },
  { id: 'p-004', type: 'pairing', title: '카페에서 모르는 사람의 대화 + 단편소설', body: '주변 사람의 말 토막에서 인물을 상상해 짧은 글로 옮겨본다. 글쓰기 근육이 풀린다.', tags: ['글쓰기'], origin: 'seed' },
  { id: 'p-005', type: 'pairing', title: '걷기 + 팟캐스트', body: '익숙한 길을 새 팟캐스트와 함께 걷는다. 풍경과 목소리가 서로의 인상을 짙게 만든다.', tags: ['일상'], origin: 'seed' },
  { id: 'p-006', type: 'pairing', title: '세잔의 정물화 + 사과 한 알', body: '실제 사과를 두고 그림을 본 다음, 사과를 한 입 베어물어 본다. 화가가 본 것을 더 잘 이해하게 된다.', tags: ['예술','감각'], origin: 'seed' },
  { id: 'p-007', type: 'pairing', title: '쇼팽 + 가을 산책', body: '"녹턴 op.9" 을 들으며 잎이 떨어지는 길을 걸어본다. 음악과 계절은 같은 어휘를 쓴다.', tags: ['음악','계절'], origin: 'seed' },
  { id: 'p-008', type: 'pairing', title: '"바람의 검심" + 인스턴트 라면', body: '오래된 만화를 다시 펼치면 그 시절의 라면 맛이 같이 돌아온다. 기억은 미각으로도 저장된다.', tags: ['추억'], origin: 'seed' },
  { id: 'p-009', type: 'pairing', title: '데이비드 호크니 + 수영장', body: '호크니의 수영장 그림을 보고, 가능한 빨리 물에 들어가본다. 같은 파란색이 다르게 보인다.', tags: ['예술'], origin: 'seed' },
  { id: 'p-010', type: 'pairing', title: '맑은 밤 + NASA APOD', body: '오늘의 천체 사진을 본 뒤 밖에 나가 같은 별을 찾아본다. 우주는 갑자기 가까워진다.', tags: ['우주'], origin: 'seed' },
];
